name: CI

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - '.github/workflows/ci.yml'
  pull_request:
    branches:
      - master
    paths:
      - '**.py'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  test:
    env:
      EMAIL: ${{ secrets.MEGA_EMAIL }}
      PASS: ${{ secrets.MEGA_PASS }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", 3.13]
      fail-fast: false
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync

      - name: Run pytest
        run: |
          uv run pytest
