name: Ruff
on: [push, pull_request]

permissions: {}

jobs:
  ruff:
    name: Lint and check format
    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: ruff
        uses: astral-sh/ruff-action@v4.1.0

      - run: ruff format --check --diff --output-format github
        if: ${{ !cancelled() }}
